// _id: 5ec7ade2d9568d22c8f4fd89 generated by mongo db driver, so we dont need to wait to mongo to generate a unique identifier.

// 12 bytes (1 byte = 8 bits)
    // 4 bytes: timestamp
    // 3 bytes: machine identifier
    // 2 bytes: process identifier
    // 3 bytes: counter

//GENERATE OUR OWN ID
const mongoose = require('mongoose')

const id = new mongoose.Types.ObjectId();

console.log(id.getTimestamp())

const isvalid = mongoose.Types.ObjectId.isValid('123')

console.log(isvalid)

